name: Pyright Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.398
          python-version: 3.11
