name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            ./.tests/requirements-dev.txt

      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update

      - name: Install Python dependencies
        run: /usr/bin/python3 -m pip install -r ./.github/requirements-test.txt

      - name: Run tests
        run: /usr/bin/python3 -m pytest ./.test/ -vvvv -rP
